import './globals.css'; // Ensure you import your global CSS (located in /app)

export const metadata = {
  title: 'Next.js App',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* You can add metadata tags here */}
      </head>
      <body>{children}</body>
    </html>
  );
}
